### ISSUE TITLE
Please fix the "powershell" command for PowerShell Core

### ISSUE THREAD

**Issue by wzjing** [microsoft/glTF-SDK#30]
- System: macOS 10.13.6
- Branch: master

It looks like the latest PowerShell Core on mac and linux use `pwsh` to execute command instead of `powershell`. So, the 17th line in [CMakeList.txt](https://github.com/Microsoft/glTF-SDK/blob/master/GLTFSDK/CMakeLists.txt) will cause an error when I trying to compile this project.

**Comment by kokuda** [comment]
This is probably a good idea since more clients seem to have "pwsh" than "powershell".  The alternative is to support both in some way, which is easy enough to do from within powershell, but might be hard to do from within cmake.

For now, you can work around the issue by creating a symbolic link from powershell to pwsh in /usr/local/bin

**Comment by jlisee** [comment]
[`find_program`](https://cmake.org/cmake/help/v3.0/command/find_program.html) can be used here so we can do something like:

```cmake
find_program(POWERSHELL_PATH NAMES pwsh powershell)

add_custom_command(
    OUTPUT ${CMAKE_BINARY_DIR}/GeneratedFiles/SchemaJson.h
    COMMAND ${POWERSHELL_PATH} -ExecutionPolicy Bypass "${CMAKE_CURRENT_LIST_DIR}/GenerateSchemaJsonHeader.ps1" -outPath "${CMAKE_BINARY_DIR}/GeneratedFiles"
    WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
    DEPENDS "${schema_deps}"
)
```

**Comment by chriche-ms** [comment]
@jlisee Thanks for the suggestion, it's a neat solution :)
