### ISSUE TITLE
Target webassembly

### ISSUE THREAD

**Issue by unicomp21** [microsoft/glTF-SDK#46]
From a procgen perspective, ie generating assets within the browser, being able to compile gltf sdk as webassembly would be "huge".

**Comment by chriche-ms** [comment]
We've experimented with compiling glTF-SDK as webassembly some time ago. The good news is that very few changes are required to get everything building and working (just a few minor changes to the CMakeList.txt files). You could easily do this in a fork of the repo.

Bringing the changes back into master branch would be more problematic as many of the unit tests fail due to having dependencies on external file and resources. Also, updating the DevOps build to install and use emscripten was more effort than we wanted to spend on functionality that we didn't intend to use in the short term.

Finally, you will likely need to write custom std::iostream derived types to interface between the wasm module and browser environment which could be tricky depending on the level of performance you need.
